import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import GuestbookEntryInput from '../components/GuestbookEntryInput';
import GuestbookEntriesList from '../components/GuestbookEntriesList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <div className='flex flex-row justify-end px-10 py-4'>
          <ConnectButton />
        </div>
        <div className='flex flex-col justify-center items-center'>
          <GuestbookEntryInput />
          <GuestbookEntriesList />
        </div>
      </main>
    </div>
  );
};

export default Home;
